# Generated by Django 3.2.7 on 2021-10-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20211001_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='selfi',
            field=models.CharField(default=' ', max_length=80),
        ),
        migrations.AddField(
            model_name='jugador',
            name='selfi',
            field=models.CharField(default=' ', max_length=80),
        ),
        migrations.AddField(
            model_name='liga',
            name='selfi',
            field=models.CharField(default=' ', max_length=80),
        ),
    ]
