# Generated by Django 3.2.7 on 2021-10-01 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('league', models.CharField(default=' ', max_length=100)),
                ('players', models.CharField(default=' ', max_length=100)),
                ('self', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='liga',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('teams', models.CharField(default=' ', max_length=100)),
                ('players', models.CharField(default=' ', max_length=100)),
                ('self', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jugador',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('time_trained', models.IntegerField(default=0)),
                ('league', models.CharField(default=' ', max_length=100)),
                ('team', models.CharField(default=' ', max_length=100)),
                ('self', models.CharField(default=' ', max_length=100)),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.liga'),
        ),
    ]
