# Generated by Django 3.2.7 on 2021-10-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='selfi',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='selfi',
        ),
        migrations.RemoveField(
            model_name='liga',
            name='selfi',
        ),
    ]
